name: 'fashionable_analytics'
version: '1.0.0'
config-version: 2

profile: 'fashionable_analytics'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  fashionable_analytics:
    +schema: seeds
    +quote_columns: false

models:
  fashionable_analytics:
    staging:
      +materialized: view
      +schema: staging
      +tags: ['staging', 'fashionable']
    marts:
      +materialized: table
      dimensions:
        +schema: marts
        +tags: ["dim"]
      facts:
        +schema: marts
        +tags: ["fact"]
